"""Add country_code and multi-currency support to Account

Revision ID: a0461704cd9a
Revises: 3fed68dd5d41
Create Date: 2026-01-07 12:21:57.545480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0461704cd9a'
down_revision: Union[str, Sequence[str], None] = '3fed68dd5d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('account', sa.Column('iban', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='ACTIVE'))
    op.add_column('account', sa.Column('risk_score', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='LOW'))
    op.create_index(op.f('ix_account_iban'), 'account', ['iban'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_iban'), table_name='account')
    op.drop_column('account', 'risk_score')
    op.drop_column('account', 'status')
    op.drop_column('account', 'iban')
    op.drop_column('account', 'country_code')
    # ### end Alembic commands ###
